#!/bin/bash
crontab -l | cut -c 3- | crontab
ps aux | grep "python3 start_cost_basis.py config/prod.json ETH-USD" | grep -v grep > /dev/null
if [ $? != 0 ]
then
    echo "Starting ETH"
    python3 start_cost_basis.py config/prod.json ETH-USD & > /dev/null
    sleep 5
fi

ps aux | grep "python3 start_cost_basis.py config/prod.json LTC-USD" | grep -v grep > /dev/null
if [ $? != 0 ]
then
    echo "Starting LTC"
    python3 start_cost_basis.py config/prod.json LTC-USD & > /dev/null
    sleep 5
fi

ps aux | grep "python3 balance_logger.py config/prod.json" | grep -v grep > /dev/null
if [ $? != 0 ]
then
    echo "Starting balance logger"
    python3 balance_logger.py config/prod.json & > /dev/null
fi