#!/bin/bash

PATH=/usr/bin:/bin:/root/Trader
ps aux | grep "start_cost_basis.py" | grep "config/prod.json" | grep "ETH-USD" | grep -v grep > /dev/null
if [ $? != 0 ]
then
    echo "Starting ETH"
    python3 /root/Trader/start_cost_basis.py /root/Trader/config/prod.json ETH-USD & > /dev/null
    sleep 5
fi

ps aux | grep "start_cost_basis.py" | grep "config/prod.json" | grep "LTC-USD" | grep -v grep > /dev/null
if [ $? != 0 ]
then
    echo "Starting LTC"
    python3 /root/Trader/start_cost_basis.py /root/Trader/config/prod.json LTC-USD & > /dev/null
    sleep 5
fi

ps aux | grep "balance_logger.py" | grep "config/prod.json" | grep -v grep > /dev/null
if [ $? != 0 ]
then
    echo "Starting balance logger"
    python3 /root/Trader/balance_logger.py /root/Trader/config/prod.json & > /dev/null
fi

crontab -l | perl -nle 's/^#\s*([0-9*])/$1/;print' | crontab